### PR TITLE
Fix/scrollbar not working if the target is html

### LINKED ISSUE #1338: [🐛 in esl-scrollbar]:scrollbar not working if the target is html
`esl-scrollbar` is not working when the target is set to 'html' (page root)

**To Reproduce**
1. Create a page  with an esl-scrollbar targeting root of the page (use this page for example /draft/nested-accordion/)
2. Observe the scroll

**Current behavior**
The scrollbar is not observing the window and its current overflow state

**Expected behavior**
scrollbar correctly works with the root of the page

**Environment**
- Browser: All [e.g. Chrome/Latest]

### PR DESCRIPTION
**Pull request by Natalie-Smirnova**
The visibilitytr5 and size of scroll at start was fixed

Closes #1338

### CODE REVIEW

**Review by ala-n — APPROVED** [review]

File: src/modules/esl-scrollbar/core/esl-scrollbar.ts [hunk 1]
```diff
@@ -104,16 +104,19 @@ export class ESLScrollbar extends ESLBaseElement {
...
       this._resizeObserver.observe(this.$target);
-      this._mutationObserver.observe(this.$target, {childList: true});
-      Array.from(this.$target.children).forEach((el) => this._resizeObserver.observe(el));
     }
+    // Subscribes to the child elements resizes
+    this._mutationObserver.observe(this.$target, {childList: true});
+    Array.from(this.$target.children).forEach((el) => this._resizeObserver.observe(el));
   }
 
+  /** Resubscribes resize observer on child elements when container content change */
```
Comment (NastaLeo) [inline src/modules/esl-scrollbar/core/esl-scrollbar.ts:119]:
```suggestion
  /** Resubscribes resize observer on child elements when container content changes */
```

**Review by NastaLeo — APPROVED** [review]

**Review by dshovchko — APPROVED** [review]
