### PR TITLE
fix(esl-utils): event listener utils bugfixes

### LINKED ISSUE #983: [🚀 esl-utils/listen]:  add possibility to see event handler code in the browser
As an ESL consumer I want to be able to navigate to source code of exact event handler in the browser (event listeners tab) in case event is subscribed by @listen decorator

Example:
```ts
  // We are searching for its method
  @listen('click')
  onClick(): void {
    console.log('click');
  }
```
image

### PR DESCRIPTION
**Pull request by ala-n**
Partially resolves #983

### CODE REVIEW

File: src/modules/esl-utils/dom/events/target.ts [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+      throw Error('addEventListener callback should be function or EventListenerObject');
+    }
+    this._listeners.add(callback);
+  }
+
+  public removeEventListener(callback: EventListenerOrEventListenerObject): void;
+  public removeEventListener(type: 'change', callback: EventListenerOrEventListenerObject): void;
+  public removeEventListener(type: any, callback: EventListenerOrEventListenerObject = type): void {
+    if (!callback || typeof callback !== 'function' && typeof callback.handleEvent !== 'function') {
+      throw Error('addEventListener callback should be function or EventListenerObject');
```
Comment (dshovchko) [inline src/modules/esl-utils/dom/events/target.ts:22]: Message repeats, also a condition

**Review by dshovchko — APPROVED** [review]

**Review by abarmina — APPROVED** [review]
