### PR TITLE
fix(esl-panel-group): `has-opened` attribute inconsistent behavior

### LINKED ISSUE #2082: [🔧 esl-panel-group]: internal check for `has-opened` is inconsitent
As a consumer/architect, I want to have consistent and clear conditions for `esl-panel-group` component behavior.

**Current state:**
 - initial `has-opened` state = `this.$activePanels.length > 0` which is logical
 - on panels state change, it is updated with the event panel state `this.toggleAttribute('has-opened', panel.open);` which is inconsistent

**Expected behavior:**
 - `this.$activePanels.length > 0` - the only criteria to set `has-opened` state

**Scope**
 - Cover `has-opened` marker state with unit tests
 - Make behavior consistent

Originally proposed by @andreybelous

### PR DESCRIPTION
**Pull request by fshovchko**
Closes #2082

### CODE REVIEW

**Review by dshovchko — APPROVED** [review]

File: src/modules/esl-panel-group/core/esl-panel-group.ts [hunk 1]
```diff
@@ -105,11 +105,15 @@ export class ESLPanelGroup extends ESLBaseElement {
 
     this.updateModeCls();
     this.reset();
-    this.toggleAttribute('has-opened', this.$activePanels.length > 0);
+    this.updateOpenState();
 
     if (prevMode !== currentMode) this.$$fire(this.MODE_CHANGE_EVENT, {detail: {prevMode, currentMode}});
   }
 
+  protected updateOpenState(): void {
```
Comment (ala-n) [inline src/modules/esl-panel-group/core/esl-panel-group.ts:113]:
```suggestion
  protected updateMarkers(): void {
```

**Review by ala-n — APPROVED** [review]

**Review by NastaLeo — APPROVED** [review]
