### PR TITLE
fix(esl-trigger): stop `click` event bubbling

### LINKED ISSUE #3231: [🐛 in esl-note]: click on note bubbles and has side effects

### PR DESCRIPTION
**Pull request by NastaLeo**
closes #3231

### CODE REVIEW

File: packages/esl/src/esl-trigger/core/esl-base-trigger.ts [hunk 1]
```diff
@@ -17,6 +17,8 @@ export abstract class ESLBaseTrigger extends ESLBaseElement {
   @prop('') public CHANGE_EVENT: string;
   /** Events to observe target {@link ESLToggleable} instance state */
   @prop('esl:show esl:hide') public OBSERVED_EVENTS: string;
+  /** Marker to stop event bubbling */
+  @attr({defaultValue: true}) public stopPropagation: boolean;
```
Comment (ala-n) [inline packages/esl/src/esl-trigger/core/esl-base-trigger.ts:21]:
```suggestion
  @attr({defaultValue: true, parser: parseBoolean}) public stopPropagation: boolean;
```

**Review by ala-n — APPROVED** [review]
